language: java
jdk: oraclejdk8
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: AVzZwF9HsHHVJ5UokyIyqJ5f+OKuw6wArIKgVdVKZAYsoyqpFrueNMQqRopTEloGmsHTroKDelOytf8DfTOVBAi8KPlLNvkit5kVlgAAK5OqT9nf/YoCPZ3dgx7PGYCjsC4AVPPMaZvmo9w8uD2Ga30UOa4VKI4CsBLrCuBIdQKfSa6Mpqs9cM4iX4C8IhgopZFEibtxwayYIZLqkVPzSkML3L50eCKJ0kTr/KJQpJiR6/5fEOMMIYeSOpNs3y60PRqoBo4XJRlta7b9iQhGGaHltFznqAHsI8fp+7szVjsQzqSJSbu2I833sF56ncLavJPJfF74Itz/p2IXRka2TOsvGpd4RXKh6BqwAXYbUTrN0TQBmBu8ld74LrH3k0+ON9NzZzVXcDEDuljB0v8TGZCH2PRSTcaJZBUw8cs1INnmgcA3vBSbIbpa7f8V1kgnyzqwUKYiPt+rtfMgQ+mkGB0aNyP5hQIWX5FjOay0fvgp4oNo6+yM3FTMb3Q5012H0CxgIAAlZMSniO14ro/OlEkkwcv0IQMmOJIj+OKO7KE6VebPjVTrLVYUThzj5RYA/MB0v/auBODi29QHCo3/hVGhX0UnlKrpOy+SJFTptnJyPV8Q6QgA/t0vwq+qqfx05gf9G/axwXtM6zrJRSjubbTXOEZVn+5/10X0CQ0QjQc=
